import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './globals.css'

const redHatDisplay = Red_Hat_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <Theme>
      <body className={redHatDisplay.className}>{children}</body>
      </Theme>
    </html>
  )
}
