import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'
import '@radix-ui/themes/styles.css'
import './globals.css'

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-redHatDisplay',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={redHatDisplay.variable}>{children}</body>
    </html>
  )
}
